---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 12.03.2023 17:58
---
function CreateBossIntro()
    CreateMoveTextureTimed(5)
end
function CreateMoveTextureTimed(duration)
    local parenBOX=BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetParent(parenBOX, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    local elements={}
    local xs,ys=-2,0.3
    local size=0.12
    for i=0,64 do
        local element = BlzCreateFrameByType("BACKDROP", "Face", parenBOX, "", 0)
        BlzFrameSetTexture(element, "IceLeft2Right", 0, true)
        BlzFrameSetSize(element, size, size)
        BlzFrameSetAbsPoint(element,FRAMEPOINT_CENTER,xs+size*i,ys)
        table.insert(elements,element)
    end
    local speed=0.01
    local x=0
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", parenBOX, "", 0)
    BlzFrameSetAbsPoint(text,FRAMEPOINT_CENTER,0.4,0.3)
    BlzFrameSetText(text, ColorText2Black("Сытый Етти"))
    BlzFrameSetScale(text, 6)

    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        x=x+speed
        duration=duration-TIMER_PERIOD
        for i=1,#elements do
            BlzFrameSetAbsPoint(elements[i],FRAMEPOINT_CENTER,x+xs+size*i,ys)
        end
        if duration <= 0 then
            DestroyTimer(GetExpiredTimer())
            BlzDestroyFrame(parenBOX)
        end
    end)
end