---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 16.02.2023 22:32
---
function PlayBossSpeech(sound, text)
    if not TexBoxBoss then
        --print("первый диалог")
        CreteDialogBoxBoss()
    end
    if not BlzFrameIsVisible(TexBoxBoss) then
        local s = normal_sound(sound)
        local sd = GetSoundDuration(s)
        --SetCinematicScene(HeroID, 1, "peon", "text", 2, 2)
        if sd <= 10 then
            sd = 1000
        end
        BlzFrameSetVisible(TexBoxBoss, true)
        BlzFrameSetText(TexBoxTextBoss, text)
        --TransmissionFromUnitWithNameBJ(GetPlayersAll(), HERO[0].UnitHero, "", nil, "", bj_TIMETYPE_SET, GetSoundDuration(s) / 700, false)
        --print(GetSoundDuration(s))
        TimerStart(CreateTimer(), sd / 700, false, function()
            BlzFrameSetVisible(TexBoxBoss, false)
        end)
    end
end

function CreteDialogBoxBoss()
    --print("создан бокс ",toolTipTex)
    local tooltip = BlzCreateFrameByType("FRAME", "TestDialog", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "StandardFrameTemplate", 0)
    BlzFrameSetParent(tooltip, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    --local backdrop = BlzCreateFrame("QuestButtonDisabledBackdropTemplate", tooltip, 0, 0)
    local backdrop = BlzCreateFrameByType("BACKDROP", "Face", tooltip, "", 0)
    BlzFrameSetTexture(backdrop, "SpeechBoxBoss", 0, true)


    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", tooltip, "", 0)
    BlzFrameSetAbsPoint(tooltip, FRAMEPOINT_LEFT, 0, 0.09)
    BlzFrameSetSize(tooltip, 0.25, 0.125)
    BlzFrameSetSize(backdrop, 0.25, 0.125)
    BlzFrameSetSize(text, 0.28, 0.06)
    BlzFrameSetPoint(backdrop, FRAMEPOINT_CENTER, tooltip, FRAMEPOINT_CENTER, 0.0, 0.0)
    --BlzFrameSetAlpha(backdrop, 0)
    BlzFrameSetText(text, "Проверочный текст для фрейма теперь текста больше, а где авто перенос?,Проверочный текст для фрейма теперь текста больше, а где авто перенос?,Проверочный текст для фрейма теперь текста больше, а где авто перенос?,Проверочный текст для фрейма теперь текста больше, а где авто перенос?")
    BlzFrameSetPoint(text, FRAMEPOINT_LEFT, tooltip, FRAMEPOINT_LEFT, 0.02, -0.003)
    BlzFrameSetScale(text, 0.8)
    BlzFrameSetVisible(tooltip, false)

    TexBoxBoss = tooltip
    TexBoxTextBoss = text
end