---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 16.02.2023 22:32
---
GBossSoundDuration = 0
function PlayBossSpeech(sound, text)
    if not TexBoxBoss then
        --print("первый диалог")
        CreteDialogBoxBoss()
    end
    if not text then
        text = "У меня нет слов"
    end
    local s = nil
    if not BlzFrameIsVisible(TexBoxBoss) and UnitAlive(GBoss) then
        s = normal_sound(sound)
        if GetUnitTypeId(GBoss) == FourCC("n007") then
            -- мясник говорит ниже
            SetSoundPitch(s, 0.8)
        end
        local sd = GetSoundDuration(s)
        --SetCinematicScene(HeroID, 1, "peon", "text", 2, 2)
        if sd <= 10 then
            sd = 3000
        end
        GV = 20
        SetMusicVolumeBJ(GV)
        BlzFrameSetVisible(TexBoxBoss, true)
        BlzFrameSetText(TexBoxTextBoss, text)
        --BlzFrameSetScale(TexBoxTextBoss, GetTextScaleForBoss(text))
        --TransmissionFromUnitWithNameBJ(GetPlayersAll(), HERO[0].UnitHero, "", nil, "", bj_TIMETYPE_SET, GetSoundDuration(s) / 700, false)
        --print(GetSoundDuration(s))
        GBossSoundDuration = sd / 700
        local chkTimer = CreateTimer()
        TimerStart(CreateTimer(), 0.5, true, function()
            if not UnitAlive(GBoss) then
                StopSound(s, false, 0.5)
                DestroyTimer(chkTimer)
            end
        end)
        TimerStart(CreateTimer(), sd / 700, false, function()
            BlzFrameSetVisible(TexBoxBoss, false)
            DestroyTimer(chkTimer)
            TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
                SetMusicVolumeBJ(GV)
                GV = GV + 1
                if GV >= 100 then
                    DestroyTimer(GetExpiredTimer())
                end
            end)
        end)
    end
    return s
end

function CreteDialogBoxBoss()
    local testText = "А с другой стороны и хорошо, что вы пришли, мне надоело дёргать своего одноглазого змея под ваши звуки"
    --local scale = GetTextScaleForBoss(testText)
    local tooltip = BlzCreateFrameByType("FRAME", "TestDialog", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "StandardFrameTemplate", 0)
    BlzFrameSetParent(tooltip, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    local backdrop = BlzCreateFrameByType("BACKDROP", "Face", tooltip, "", 0)
    BlzFrameSetTexture(backdrop, "SpeechBoxBoss", 0, true)
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", tooltip, "", 0)
    BlzFrameSetAbsPoint(tooltip, FRAMEPOINT_LEFT, 0.0, 0.09)
    local sw, sh = 0.3, 0.15
    BlzFrameSetSize(tooltip, sw, sh)
    BlzFrameSetSize(backdrop, sw, sh)
    BlzFrameSetSize(text, sw * 0.85, sh * 0.5)
    BlzFrameSetPoint(backdrop, FRAMEPOINT_CENTER, tooltip, FRAMEPOINT_CENTER, 0.0, 0.0)
    BlzFrameSetText(text, testText)
    BlzFrameSetPoint(text, FRAMEPOINT_CENTER, tooltip, FRAMEPOINT_CENTER, 0, -0.027)

    BlzFrameSetScale(text, 0.8)

    BlzFrameSetVisible(tooltip, false)

    TexBoxBoss = tooltip
    TexBoxTextBoss = text
end

--BlzFrameSetScale(TexBoxTextBoss, GetTextScaleForBoss(text))

function GetTextScaleForBoss(testText)
    local k = #testText
    local scale = 1.7 - k * 0.005
    --print("максимум символов=", k, scale)
    if scale <= 0.8 then
        scale = 0.8
    end
    if scale >= 2 then
        scale = 2
    end
    --print(scale)
    return scale
end