---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 21.01.2023 23:57
---
function PlayMonoSpeech(sound,text)
    if not BlzFrameIsVisible(TexBox) then
        local s=normal_sound(sound)

        --SetCinematicScene(HeroID, 1, "peon", "text", 2, 2)

        BlzFrameSetVisible(TexBox, true)
        BlzFrameSetText(TexBoxText,text)
        TransmissionFromUnitWithNameBJ( GetPlayersAll(), HERO[0].UnitHero, "", nil, "", bj_TIMETYPE_SET, GetSoundDuration(s)/700, false )
        --print(GetSoundDuration(s))
        TimerStart(CreateTimer(), GetSoundDuration(s)/700, false, function()
            BlzFrameSetVisible(TexBox, false)
        end)
    end
end