---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 21.01.2023 23:57
---
function PlayMonoSpeech(sound, text)
    if not BlzFrameIsVisible(TexBox) then
        local s = normal_sound(sound)
        local sd = GetSoundDuration(s)
        --SetCinematicScene(HeroID, 1, "peon", "text", 2, 2)
        if sd <= 10 then
            sd = 1000
        end
        BlzFrameSetVisible(TexBox, true)
        BlzFrameSetText(TexBoxText, text)
        TransmissionFromUnitWithNameBJ(GetPlayersAll(), HERO[0].UnitHero, "", nil, "", bj_TIMETYPE_SET, GetSoundDuration(s) / 700, false)
        --print(GetSoundDuration(s))
        TimerStart(CreateTimer(), sd / 700, false, function()
            BlzFrameSetVisible(TexBox, false)
        end)
    end
end

function RandomRescueSpeech()
local path="Speech\\Peon\\Rescue\\"
    local table = {
        [1] = {
            text = "Иди на работу",
            sound = path.."idinaraboty"
        },
        [2] = {
            text = "И тут же он отрубился",
            sound = path.."itytzheonotrybilsa"
        },
        [3] = {
            text = "Ой, я случайно",
            sound = path.."oiyaslychaino"
        },
        [4] = {
            text = "Я не хотел, брат",
            sound = path.."yanehotelbrat"
        }
    ,
        [5] = {
            text = "Это просто моя работа, вырубать таких лентяев как ты",
            sound = path.."etoprostomoyarabota"
        }
    ,
        [6] = {
            text = "Осторожно, скользко",
            sound = path.."ostorozhnoskolsko"
        }
    ,
        [7] = {
            text = "Просто, демонстрация силы",
            sound = path.."prostodemonstraciasili"
        }
    ,
        [8] = {
            text = "Внимательней будь",
            sound = path.."vnimatelneybud"
        }
    ,
        [9] = {
            text = "Выписан из пролетариата",
            sound = path.."vipisanizproletariata"
        }
    ,
        [10] = {
            text = "Как бы я хотел лечь и отдохнуть, так же как и он",
            sound = path.."kakbiyahotel"
        }
    ,
        [11] = {
            text = "Это всё потому, что ты стоишь и не работаешь",
            sound = path.."etovsepotomychtotistoish"
        }
    ,
        [12] = {
            text = "Запомни брат такую фразу: тебе попал в ебало сразу",
            sound = path.."zapomnibrattakyufrazy"
        }
    ,
        [13] = {
            text = "Брат, такова твоя судьба, сломал тебе я пол-ебла",
            sound = path.."brattakovatvoyasydba"
        }
    ,
        [14] = {
            text = "Вот и выхватил ты бодрых пиздов, лежишь и никаких делов",
            sound = path.."votavihvatiltibodrishpizdov"
        }
    ,
        [15] = {
            text = "Услышь моё ты возраженье, вьбу я на опереженье",
            sound = path.."yslishmoyotivozrashenie"
        }

    }
    local number = GetRandomInt(1, #table)
    --print(number)
    -- print(table[number].text)
    if number > #table then
        number = #table
        print("фраза вне диапазона")
    end
    PlayMonoSpeech(table[number].sound, table[number].text)
end