---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 26.03.2023 14:27
---
function CreateBeemLighting(hero,x,y,xEnd,yEnd,timed)
    x,y=GetUnitXY(hero)
    local angle=GetUnitFacing(hero)
    local eff=AddSpecialEffect("LightOnly",x,y)
    local z=GetTerrainZ(x,y)+80
    BlzSetSpecialEffectZ(eff,z)
    BlzSetSpecialEffectPitch(eff, math.rad(-90))
    BlzSetSpecialEffectYaw(eff, math.rad(-180+angle))
    BlzPlaySpecialEffect(eff,ANIM_TYPE_STAND)
    BlzSetSpecialEffectMatrixScale(eff,1.5,1.5,5)
end