---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 23.11.2023 22:40
---
function PlayPudgeSpeechNumber(n)
    local BD={
        "Что это ещё там за скрипы...",
        "Показалось?",
        "Наверное кто-то идёт?",
        "Нет, ну точно кто то ломится!",
        "Если это опять эти зелёные Эльфы - пущу их на мясо",
        "Эй, а по тише там можно?",
        "Я же там ловушек понаставил, вряд ли они пройдут дальше",
        "Там даже лестниц нет чтобы подниматься на верх",
        "Пришло время активировать самые сложные ловушки!",
        "Да сколько можно!?",
        "Павел, а на тебе сейчас есть штаны?"
    }
    if not GBoss then
        GBoss=FindUnitOfType(FourCC("n007"))
        --print('мясник инициализирован')
    end
    CameraSetEQNoiseForPlayer(Player(0), 6)
    TimerStart(CreateTimer(), 2, false, function()
        CameraClearNoiseForPlayer(Player(0))
    end)
    local s=PlayBossSpeech("Speech\\Pudge\\Q"..n,BD[n] )
    SetSoundPitch(s, 0.8)

end