---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 23.11.2023 22:40
---
function PlayPudgeSpeechNumber(n)
    local BD = {
        "Что это ещё там за скрипы...",
        "Показалось?",
        "Наверное кто-то идёт?",
        "Нет, ну точно кто то ломится!",
        "Если это опять эти зелёные Эльфы - пущу их на мясо",
        "Эй, а по тише там можно?",
        "Я же там ловушек понаставил, вряд ли они пройдут дальше",
        "Там даже лестниц нет чтобы подниматься на верх",
        "Пришло время активировать самые сложные ловушки!",
        "Да сколько можно!?",
        "Павел, а на тебе сейчас есть штаны?",
        "Я уже готов принимать гостей, когда прейдёте, то пополню счетчик ваших смертей",
        "Вот и открыли вы последний проход, угадайте, кто вас внизу сидит ждёт?",
        "Про последний проход я соврал, ещё не скоро здесь будет финал",
        "Варенье вы пришли украсть? Но угодите прям ко мне в пасть"
    }
    --if not GBoss then
    GBoss = FindUnitOfType(FourCC("n007"))
    --print('мясник инициализирован')
    --end
    CameraSetEQNoiseForPlayer(Player(0), 6)

    PlayBossSpeech("Speech\\Pudge\\Q" .. n, BD[n])

    local portrait = BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetParent(portrait, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(portrait, GetPortraitFromBD(nil), 0, true)
    BlzFrameSetSize(portrait, 0.06, 0.06)
    BlzFrameSetAbsPoint(portrait, FRAMEPOINT_LEFT, -0.05, 0.05)
    StunUnit(udg_HERO, 2)
    SetUnitAnimationByIndex(udg_HERO,20) --падение
    TimerStart(CreateTimer(), GBossSoundDuration, false, function()
        BlzDestroyFrame(portrait)
        CameraClearNoiseForPlayer(Player(0))
    end)
    --table.insert(BugsFH,portrait)
end
