---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 02.04.2023 16:47
---
function StartPeonAllyAI()
    local unit = FindUnitOfType(FourCC('o002'))
    local hero = HERO[0].UnitHero

    --print("союзник активирован")
    local reactSpeed = 1
    BlzSetUnitMaxHP(unit, 5000)
    HealUnit(unit)
    UnitAddAbility(unit, FourCC("Abun"))
    TimerStart(CreateTimer(), 1, true, function()
        local xh, yh = GetUnitXY(hero)
        local boss = FindFirstEnemy(unit,2000)
        if boss then
            if not IsUnitInRange(unit, hero, 800) then
                IssuePointOrder(unit, "move", xh, yh)

            else
                if IsUnitInRange(unit, boss, 1500)  and UnitAlive(boss) and UnitAlive(unit)  then
                    SetUnitFacingToFaceUnitTimed(unit, boss, 0)
                    --print("пора атаковать")

                    AllyAttackBoss(unit)

                    IssueImmediateOrder(unit, "stop")
                end
            end
        end

        if AllyPeonCanTP then
            if not IsUnitInRange(unit, hero, 2000) then
                Blink2Point(unit,GetUnitXY(hero))
            end
        end
        if not UnitAlive(unit) then
            DestroyTimer(GetExpiredTimer())
            PlayMonoSpeech("Speech\\Peon\\yabessmertniy", "Жил до конца, умер как герой")
        end
    end)
    --

    local DamageTrigger = CreateTrigger()
    TriggerRegisterUnitEvent(DamageTrigger, unit, EVENT_UNIT_DAMAGED) -- После вычета брони
    DestroyEffect(AddSpecialEffectTarget("Effect\\Concecration", unit, "chest"))
    TriggerAddAction(DamageTrigger, function()
       -- print("ПОЛУЧИЛ УРОН!")
        DisableTrigger(DamageTrigger)
        local angle = GetRandomInt(0, 360)
        UnitAddJumpForce(unit, angle, 40, 300, 500, false)
        SetUnitInvulnerable(unit, true)
        TimerStart(CreateTimer(), 1, false, function()
            SetUnitInvulnerable(unit, false)
            EnableTrigger(DamageTrigger)
        end)
    end)
end

function AllyAttackBoss(unit, boss)
    SetUnitAnimation(unit, "Attack")
    TimerStart(CreateTimer(), 0.2, false, function()
        if not BlzIsUnitInvulnerable(unit) then
            local angle = GetUnitFacing(unit)
            CreateAndForceBullet(unit, angle, 40, "Melee")
            QueueUnitAnimation(unit,"stand")
        end
    end)

end

function FindNearEnemyXY(unit,range,x,y)
    local e = nil
    local result = nil
    local min=1000
    GroupEnumUnitsInRange(perebor, x, y, range, nil)
    while true do
        e = FirstOfGroup(perebor)
        if e == nil then
            break
        end

        if UnitAlive(e) and IsUnitEnemy(e, GetOwningPlayer(unit)) and not BlzIsUnitInvulnerable(e) then
            local dist=DistanceBetweenXY(x,y,GetUnitXY(e))
            if dist<=min then
                min=dist
                result = e
            end
            --print("найден для сетки",GetUnitName(e))
        end
        GroupRemoveUnit(perebor, e)
    end
    return result
end

function FindFirstEnemy(unit, range)
    local e = nil
    local result = nil
    local xs, ys = GetUnitXY(unit)
    -- DestroyEffect(AddSpecialEffect("Abilities\\Spells\\NightElf\\Blink\\BlinkCaster.mdl", xs, ys))
    GroupEnumUnitsInRange(perebor, xs, ys, range, nil)
    while true do
        e = FirstOfGroup(perebor)
        if e == nil then
            break
        end

        if UnitAlive(e) and IsUnitEnemy(e, GetOwningPlayer(unit)) and not BlzIsUnitInvulnerable(e) then
            --print("найден для сетки",GetUnitName(e))
            result = e
        end
        GroupRemoveUnit(perebor, e)
    end
    return result
end