---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 06.11.2023 17:26
---
function ReplaceId2InvisiblePlatform(id)
    local tmp, k, all = FindUnitOfType(id)
    --print("найденно "..k.." а в таблице "..#all)
    for i = 1, #all do
        -- print("заменён "..GetUnitName(all[i]))
        ShowUnit(all[i], false)
        SetUnitInvulnerable(all[i], true)
        CreateInvPlatform(all[i])
    end
end

function CreateInvPlatform(hero)
    local x, y = GetUnitXY(hero)
    local enterTrig = CreateTrigger()
    TriggerRegisterUnitInRange(enterTrig, hero, 100, nil)
    local free=true
    TriggerAddAction(enterTrig, function()
        local enemy = GetTriggerUnit()
        --print(GetUnitName(enemy).. "Вошел в зону ловушки")
        free=false
        if not free then
            local eff = AddSpecialEffect("footswitchWhite", x, y)
            --BlzSetSpecialEffectColorByPlayer(eff, Player(1)) -- синий
            local r=GetRandomInt(0,255)
            local r2=GetRandomInt(0,255)
            local r3=GetRandomInt(0,255)
            BlzSetSpecialEffectColor(eff,r,r2,r3)
            CreateEffectDown2Up(eff, x, y)
            TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
                if not IsUnitInRange(hero, enemy, 110) or not UnitAlive(enemy) then
                    DestroyTimer(GetExpiredTimer())
                    free=true
                    CreateEffectUp2Down(eff, x, y)
                    --print("вышел")
                end
            end)
        end
    end)
end

function CreateEffectDown2Up(eff, x, y)
    BlzSetSpecialEffectColorByPlayer(eff, Player(1))
    local z = GetTerrainZ(x, y) - 500
    local zNormal = GetTerrainZ(x, y) - 50
    BlzSetSpecialEffectZ(eff, z)
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        z = z + 50
        BlzSetSpecialEffectZ(eff, z)
        if z >= zNormal then
            DestroyTimer(GetExpiredTimer())
        end
    end)
end

function CreateEffectUp2Down(eff, x, y)
    BlzSetSpecialEffectColorByPlayer(eff, Player(1))
    local zNormal = GetTerrainZ(x, y) - 500
    local z = GetTerrainZ(x, y) - 50
    BlzSetSpecialEffectZ(eff, z)
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        z = z - 50
        BlzSetSpecialEffectZ(eff, z)
        if z <= zNormal then
            BlzSetSpecialEffectPosition(eff, OutPoint, OutPoint, 0)
            DestroyEffect(eff)
            DestroyTimer(GetExpiredTimer())
        end
    end)
end

OutPoint=5000