---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 29.10.2023 18:24
---
function InitPendulum(id)
    local _, k, rg = FindUnitOfType(id)
    print(k, "Маятников запущено")
    for i = 1, #rg do
        --local unit = rg[i]
        StartPendulumAI(rg[i])
    end
end




function StartPendulumAI(unit)
    --local hero = HERO[0].UnitHero
    local sec=1
    local x,y=GetUnitXY(unit)
    local angle=GetUnitFacing(unit)
    UnitAddAbility(unit, FourCC("Aloc"))
    SetUnitTimeScale(unit,0)
    TimerStart(CreateTimer(), 1, true, function()
        sec = sec - 1
        print(sec)
        if sec <= 0 then
            sec = 16
            --if IsUnitInRange(unit, hero, 1000) and UnitAlive(unit)  then
            print("запускаем маятник")
            SetUnitAnimation(unit,"Attack")
            SetUnitTimeScale(unit,1)
            TimerStart(CreateTimer(), 3, false, function()
                print("время начинать наносить урон")
                local xs,ys=MoveXY(x,y,750,angle)
                local speed=16
                local dist=0
                local damageTimer=CreateTimer()
                DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Human\\HolyBolt\\HolyBoltSpecialArt", xs,ys))
                TimerStart(damageTimer, TIMER_PERIOD, true, function()
                    dist=dist+speed
                    local nx,ny=MoveXY(xs,ys,dist,angle-180)
                    DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Human\\HolyBolt\\HolyBoltSpecialArt", nx,ny))
                    --SetUnitAnimation(unit,"Attack")
                end)
                TimerStart(CreateTimer(), 3, false, function()
                   DestroyTimer(damageTimer)
                    print("урон больше не наносим, ждём движения назад")
                    --SetUnitAnimation(unit,"Attack")
                    --SetUnitTimeScale(unit,0)
                end)
            end)
            --end
        end
        if not UnitAlive(unit) then
            DestroyTimer(GetExpiredTimer())
        end
    end)
end