---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 04.02.2023 21:54
---
do
    local InitGlobalsOrigin = InitGlobals
    function InitGlobals()
        InitGlobalsOrigin()
        TimerStart(CreateTimer(), .01, false, function()
            InitSnowMan(FourCC("h005"))
            InitDeathEventCreep()
        end)
    end
end
CreepsX={}
CreepsY={}
function InitSnowMan(id)
    local _, k, rg = FindUnitOfType(id)
    --print(k,"снеговиков")
    for i = 1, #rg do
        local u = rg[i]
        CreepsX[GetHandleId(u)],CreepsY[GetHandleId(u)]=GetUnitXY(u)
    end
end

function InitDeathEventCreep()
    local this = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(this, EVENT_PLAYER_UNIT_DEATH)
    TriggerAddAction(this, function()
        local u = GetTriggerUnit() --тот кто умер
        if GetUnitTypeId(u)==FourCC("h005") then
            local killer = GetKillingUnit()
            local id=GetUnitTypeId(u)
            local p=GetOwningPlayer(u)
            local x,y=CreepsX[GetHandleId(u)],CreepsY[GetHandleId(u)]
            local delay=GetRandomInt(30,60)
            TimerStart(CreateTimer(), delay, false, function()
                local new=CreateUnit(p,id,x,y,GetRandomInt(0,360))
                CreepsX[GetHandleId(new)],CreepsY[GetHandleId(new)]=GetUnitXY(new)


            end)
            TimerStart(CreateTimer(), delay-5, false, function()
                DestroyEffect(AddSpecialEffect("HealingWater", x,y))
            end)
        end

    end)

end