---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 05.02.2023 20:55
---
function InitScorpionAI(id)
    local _, k, rg = FindUnitOfType(id)
    --print(k, "скорпионов")
    for i = 1, #rg do
        local unit = rg[i]
        StartScorpionAI(unit)
    end
end

function StartScorpionAI(unit)
    local phase = 3
    local sec = GetRandomInt(0,5)
    local hero = HERO[0].UnitHero

    local dmgTrig = CreateTrigger()
    TriggerRegisterUnitEvent(dmgTrig, unit, EVENT_UNIT_DAMAGED)
    TriggerAddAction(dmgTrig, function()
        --print("скорпион получил урон")
        local angle = AngleBetweenUnits(unit, hero) - 180
        if onForces[GetHandleId(unit)] then
            if phase==1 then
                UnitAddForceSimple(unit, angle, 20, 200)

            end
        end
    end)

    TimerStart(CreateTimer(), 1, true, function()
        sec = sec - 1
        if sec <= 0 then
            sec = 6
            phase = GetRandomInt(1, 3)

            if IsUnitInRange(unit, hero, 1000) and UnitAlive(unit)  then
                --print("герой в радиусе")
                --print(phase)
                if phase == 1 then
                    ScorpionRunTo(unit, hero, 5)
                elseif phase == 2 then
                    ScorpionRangeAttack(unit, hero, 5)
                elseif phase == 3 then
                    ScorpioUnderGroundMove(unit, hero, 5)
                end
            end
        end
        if not UnitAlive(unit) then
            DestroyTimer(GetExpiredTimer())
        end
    end)
end

function ScorpioUnderGroundMove(unit, hero, duration)
    local angle = AngleBetweenUnits(unit, hero)
    local asp = 0.02
    SetUnitAnimationByIndex(unit, 7)
    SetUnitInvulnerable(unit,true)
    TimerStart(CreateTimer(), 0.7, false, function()
        TimerStart(CreateTimer(), asp, true, function()
            duration = duration - asp
            angle = AngleBetweenUnits(unit, hero)
            BlzSetUnitFacingEx(unit, angle)
            UnitAddForceSimple(unit, angle, 5, 60, "ScorpioRun")
            DestroyEffect(AddSpecialEffect("Objects\\Spawnmodels\\Undead\\ImpaleTargetDust\\ImpaleTargetDust.mdl", GetUnitXY(unit)))
            if GetRandomInt(1,5)==1 then
                local eff=AddSpecialEffect("Ice Shard", GetUnitXY(unit))
                BlzSetSpecialEffectScale(eff,GetRandomInt(2,3))
                UnitDamageArea(unit, 50, GetUnitX(unit), GetUnitY(unit), 80)
                TimerStart(CreateTimer(), 0.7, false, function()
                    DestroyEffect(eff)
                end)
            end

            if not UnitAlive(unit) or duration-0.7 <= 0 then
                if not UnitAlive(unit) then
                    SetUnitAnimation(unit, "death")
                else
                    SetUnitAnimationByIndex(unit, 10)
                end
                SetUnitInvulnerable(unit,false)
                DestroyTimer(GetExpiredTimer())
            end
        end)
    end)
end

function ScorpionRangeAttack(unit, hero, duration)
    local angle = AngleBetweenUnits(unit, hero)
    local asp = 0.5
    TimerStart(CreateTimer(), asp, true, function()
        duration = duration - asp
        angle = AngleBetweenUnits(unit, hero)
        BlzSetUnitFacingEx(unit, angle)
        SetUnitAnimationByIndex(unit, 2)
        CreateAndForceBullet(unit, angle, 20, "Abilities\\Weapons\\ChimaeraAcidMissile\\ChimaeraAcidMissile.mdl", nil, nil, 2, 1500,150)
        if not UnitAlive(unit) or duration <= 0 then
            if not UnitAlive(unit) then
                SetUnitAnimation(unit, "death")
            end
            DestroyTimer(GetExpiredTimer())
        end
    end)
end

function ScorpionRunTo(unit, hero, duration)

    SetUnitTimeScale(unit, 3)
    --SetUnitFacing(unit, angle)
    SetUnitAnimationByIndex(unit, 1)
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        duration = duration - TIMER_PERIOD64
        local angle = AngleBetweenUnits(unit, hero)
        SetUnitFacing(unit, angle)
        UnitAddForceSimple(unit, angle, 5, 20, "ScorpioRun")
        UnitDamageArea(unit, 50, GetUnitX(unit), GetUnitY(unit), 80)
        SetUnitAnimationByIndex(unit, 1)
        if not UnitAlive(unit) or duration <= 0 then
            SetUnitTimeScale(unit, 1)
            if not UnitAlive(unit) then
                SetUnitAnimation(unit, "death")
            end
            DestroyTimer(GetExpiredTimer())
        end
    end)
end
