---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 13.04.2022 16:56
---
function ActivateBulletTrap(unit,effect)
    SetUnitAnimation(unit,"attack")
    TimerStart(CreateTimer(), 0.3, false, function()
        local angle = GetUnitFacing(unit)
        local new = CreateAndForceBullet(unit, angle, 20, effect, nil, nil, 2, 1200,150)
        BlzSetSpecialEffectYaw(new, math.rad(angle))
    end)
end

function IsUnitInLine(unit,dist,angle,xs,ys)
    local step=40
    local range=80
    local endi=dist//step
    local inLine=false
    local x,y=xs,ys
    for i=1,endi do
        x,y=MoveXY(x,y,step,angle)
        if IsUnitInRangeXY(unit,x,y,range) then
            --print("на линии видимости")
            --DestroyEffect(AddSpecialEffect("Objects\\Spawnmodels\\Undead\\ImpaleTargetDust\\ImpaleTargetDust.mdl", x,y))
            inLine=true
            return inLine
        end
    end
    return inLine
end
