---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 11.11.2023 17:34
---
---
function StartBlackHole(unit, timed)
    local x, y = GetUnitXY(unit)
    local range = 1200
    local eff=nil
    if not timed then
        UnitAddAbility(unit, FourCC("Aloc"))
        --AddCircleAreaForUnit(unit, 2500, 9999)
        eff=AddSpecialEffect("Shadow Ball",x,y)
        BlzSetSpecialEffectZ(eff,GetTerrainZ(x,y)-200)
        BlzSetSpecialEffectScale(eff,1.2)
    else
        range = 2400
    end

    local data = HERO[0]
    local maxSpeed = 6
    local minSpeed = 0.2
    local realSpeed = 1
    local imp = range * 2
    TimerStart(CreateTimer(), 0.1, true, function()
        if udg_HoleIsWork then
            BlzSetSpecialEffectTimeScale(eff,1)
            UnitDamageArea(unit, 30, x, y, 150)
            if GetRandomInt(1,3)==1 then
                CreateHoleEffect(unit, range)
            end

            if IsUnitInRange(data.UnitHero, unit, range) then
                data.BH = unit
                local dist = DistanceBetweenXY(x, y, GetUnitXY(data.UnitHero))
                realSpeed = imp / dist
                if realSpeed >= maxSpeed then
                    realSpeed = maxSpeed
                end

                if realSpeed <= minSpeed then
                    realSpeed = minSpeed
                end
                data.BHSpeed = realSpeed
                --print(data.BHSpeed)
            else
                data.BH = nil
            end

            local e = nil
            -- local k=0
            GroupEnumUnitsInRange(perebor, x, y, range, nil)
            while true do
                e = FirstOfGroup(perebor)
                --print(GetUnitName(e), "в переборе")
                if e == nil then
                    break
                end

                if UnitAlive(e) and e ~= unit and not IsUnitType(e, UNIT_TYPE_HERO) then
                    --k=k+1
                    local angle = AngleBetweenUnits(e, unit)
                    if IsUnitInRange(e, unit, 100) then
                    else
                        local dist = DistanceBetweenXY(x, y, GetUnitXY(e))
                        realSpeed = imp / dist
                        if realSpeed >= maxSpeed then
                            realSpeed = maxSpeed
                        end

                        if realSpeed <= minSpeed then
                            realSpeed = minSpeed
                        end

                        UnitAddForceSimpleClean(e, angle, realSpeed, 50) -- типа не лагает?
                    end
                end
                GroupRemoveUnit(perebor, e)
            end
            --print("юнитов в переборе",k)
        else
            data.BH = nil
            BlzSetSpecialEffectTimeScale(eff,0)
        end
        if timed then
            timed = timed - TIMER_PERIOD64
            if timed <= 0 then
                DestroyTimer(GetExpiredTimer())
                data.BH = nil
                --print("временный БХ окончен")
            end
        end
        if not UnitAlive(unit) then
            DestroyTimer(GetExpiredTimer())
            data.BH = nil
        end
    end)
end

function CreateHoleEffect(unit, range)
    local x, y = GetUnitXY(unit)
    local ra = GetRandomInt(0, 360)
    local nx, ny = MoveXY(x, y, range, ra)
    local angle = AngleBetweenXY(nx, ny, x, y) / bj_DEGTORAD
    local eff = AddSpecialEffect("Windwalk", nx, ny)
    local rs = 10
    local timed=range/rs*1.5/100
    MoveEffectTimedWSpeed(eff, rs, angle, timed)
end