---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 08.12.2023 19:30
---
function InitAllFallenWall()
    local id = FourCC('h00V')
    local _, k, rg = FindUnitOfType(id)
    --print(k, "падающих стен")


    for i = 1, #rg do
        StartStopWall(rg[i])
    end

    -- назары
     _, k, rg = FindUnitOfType(FourCC('h00W'))
    for i = 1, #rg do
        MakeUnitInfinityBouncing(rg[i])
    end
end

function StartStopWall(unit)
    local t = CreateStompWall(unit)

    local zs = GetUnitZ(unit)
    local z = zs
    local zMax = z + 500
    local speed = 10
    local up = true
    local down = false
    local x, y = GetUnitXY(unit)

    CreateSquareDestrutablesID(x, y, FourCC("Ytlc")) -- B00H - видимый Ytlc - не проходимый

    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        if up then
            z = z + speed
            for i=1,#t do
                BlzSetSpecialEffectZ(t[i], z)
            end

            if z >= zs + 200 then -- удаление блокираторов
                local range = 128
                SetRect(GlobalRect, x - range, y - range, x + range, y + range)
                EnumDestructablesInRect(GlobalRect, nil, function()
                    local d = GetEnumDestructable()
                    RemoveDestructable(d)
                end)
            end
            if z >= zMax then
                up = false
                down = true
            end
        else
            if down then
                z = z - speed * 4
                for i=1,#t do
                    BlzSetSpecialEffectZ(t[i], z)
                end

                if z <= zs+100 then
                    down = false
                    CreateSquareDestrutablesID(x, y, FourCC("Ytlc"))
                    DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic", x, y))

                    local hero=FindNearEnemyXY(unit,250,x,y)
                    if IsUnitInRangeXY(hero, x, y, 200) then
                        local ab = AngleBetweenXY(x, y, GetUnitXY(hero))/ bj_DEGTORAD
                        UnitFallGround(hero, ab, 200,{"Stun"})
                    end
                    TimerStart(CreateTimer(), 2, false, function()
                        up = true
                    end)
                end
            end
        end

        if not UnitAlive(unit) then
            DestroyTimer(GetExpiredTimer())
            for i=1,#t do
                DestroyEffect(t[i])
                BlzSetSpecialEffectZ(t[i], z)
                BlzSetSpecialEffectPosition(t[i],OutPoint,OutPoint,0)
            end
            local range = 128
            SetRect(GlobalRect, x - range, y - range, x + range, y + range)
            EnumDestructablesInRect(GlobalRect, nil, function()
                local d = GetEnumDestructable()
                RemoveDestructable(d)
            end)
        end
    end)
end

function CreateStompWall(unit)
    UnitAddAbility(unit, FourCC("Aloc"))
    ShowUnit(unit, false)
    SetUnitInvulnerable(unit, true)
    local x, y = GetUnitXY(unit)
    local t={}
    local eff = AddSpecialEffect("ConcreteCliffFloorCenter", x, y)
    BlzSetSpecialEffectMatrixScale(eff, 2, 2, 4)

    --local eff2 = AddSpecialEffect("ConcreteCliffSide", x, y)
    --BlzSetSpecialEffectYaw(eff2, math.rad(180))
    --BlzSetSpecialEffectMatrixScale(eff2, 2, 2, 1)

    local eff2 = AddSpecialEffect("MechaImpale", x, y)
    BlzSetSpecialEffectPitch(eff2, math.rad(0))
    BlzSetSpecialEffectMatrixScale(eff2, 2,2,1)
    BlzPlaySpecialEffect(eff2, ANIM_TYPE_ATTACK)


    local eff3 = AddSpecialEffect("MechaImpale", x, y)
    --BlzSetSpecialEffectZ(eff3, z - 500)
    BlzSetSpecialEffectPitch(eff3, math.rad(180))
    BlzSetSpecialEffectMatrixScale(eff3, 2,2,1)
    BlzPlaySpecialEffect(eff3, ANIM_TYPE_ATTACK)


    table.insert(t,eff)
    table.insert(t,eff2)
    table.insert(t,eff3)
    return t
end