---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 11.11.2023 15:56
---
function HeroFixRespPos()
    local data = HERO[0]
    data.ResPointX, data.ResPointY=GetUnitXY(data.UnitHero)
end