---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 11.11.2023 21:09
---
--FlyTimer(60,GetTriggerDestructable())

function FlyTimer(max,d)
    local s
    local x,y=GetDestructableX(d),GetDestructableY(d)
    if not d then
        s=normal_sound("TikTok")
    end
    TimerStart(CreateTimer(), 1, true, function()
        if not d then
            x,y=GetUnitXY(udg_HERO)
        end
        FlyTextTagShieldXY(x,y,R2I(max),Player(0),"blue")
        max=max-1
        if max<1 then
            DestroyTimer(GetExpiredTimer())
            if not d then
                KillSoundWhenDone(s)
            end
        end
    end)
end