---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 09.11.2023 22:40
---

function ReplaceIdToSpikeTraps(id)
    local tmp, k, all = FindUnitOfType(id)
    --print("найденно "..k.." а в таблице "..#all)
    for i = 1, #all do
        --print("заменён ", GetUnitName(all[i]), i,GetUnitFacing(all[i]))

        CreateSpikeTrap(all[i])
    end
end



function CreateSpikeTrap(unit,timed)
    ShowUnit(unit, false)
    SetUnitInvulnerable(unit, true)
    UnitAddAbility(unit, FourCC("Aloc"))
    local x, y = GetUnitXY(unit)
    local z = GetUnitZ(unit)
    local eff = AddSpecialEffect("MechaImpale", x, y)
    local sec = 0
    local delay=0.01
    --BlzSetSpecialEffectZ(eff, z - 80)
    --BlzSetSpecialEffectScale(eff,1)
    --BlzSetSpecialEffectTimeScale(eff,0.3)
    --BlzPlaySpecialEffect(eff, ANIM_TYPE_STAND)
    if timed then
        UnitApplyTimedLife(unit, FourCC('BTLF'), timed)
    end
    local ta=2 -- time attack
    if GetUnitFacing(unit)>89 and GetUnitFacing(unit)<91 then
        delay=2
    end
    TimerStart(CreateTimer(), delay, false, function()
        TimerStart(CreateTimer(), 1, true, function()
            sec = sec + 1
            if sec == ta then
                BlzPlaySpecialEffect(eff, ANIM_TYPE_BIRTH)
                --print("показ birth")
                TimerStart(CreateTimer(), 0.15, false, function()
                    --print("время урона?")
                    UnitDamageArea(unit, 50, GetUnitX(unit), GetUnitY(unit), 80)
                end)
            else
                BlzPlaySpecialEffect(eff, ANIM_TYPE_STAND)
            end
            if sec >= 4 then
                sec = 0
            end
            if not UnitAlive(unit) then
                DestroyTimer(GetExpiredTimer())
                DestroyEffect(eff)
            end
        end)
    end)
end