---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.11.2023 9:13
---
---
---MoveDestructableDown(gg_dest_B00G_16112, -500, 5)
--MoveDestructableDown(GetEnumDestructable(), -500, 5)



function CreateFloorInRoom(x, y,h,w)
    if not x then
        x, y = GetDestructableX(gg_dest_DTfx_17980), GetDestructableY(gg_dest_DTfx_17980)
    end
    local step = 256
    local id = FourCC("B00G")
    local z = 896--GetTerrainZ(x,y)
    for i = 1, h do
        for k = 1, w do
            local r = GetRandomInt(1, 4)
            CreateDestructableZ(id, x + ((i - 1) * step), y - ((k - 1) * step), z, 90 * r, 2, 1)
        end
    end
end

function MoveDestructableDown(d, maxZ, speed)
    local x, y = GetDestructableX(d), GetDestructableY(d)
    local id = GetDestructableTypeId(d)
    local currentZ = GetTerrainZ(x, y)
    maxZ = currentZ + maxZ
    CreateSquareDestrutables(x, y)
    local lastD = nil
    local tmdD = d
    PlayerSeeNoiseInRangeTimed(0.5, x, y)
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        currentZ = currentZ - speed

        if currentZ <= maxZ then
            DestroyTimer(GetExpiredTimer())
            lastD = tmdD
            PlayerSeeNoiseInRangeTimed(0.5, x, y)
        else
            RemoveDestructable(d)
            d = CreateDestructableZ(id, x, y, currentZ, 0, 2, 1)
            tmdD = d
        end
    end)
end

function MoveDestructableUp(d, maxZ, speed)
    local x, y = GetDestructableX(d), GetDestructableY(d)
    local id = GetDestructableTypeId(d)
    local currentZ = GetTerrainZ(x, y) - maxZ
    maxZ = 896
    PlayerSeeNoiseInRangeTimed(0.5, x, y)
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        currentZ = currentZ + speed
        if currentZ >= maxZ then
            --print("верх!")
            DestroyTimer(GetExpiredTimer())
            RemoveTableDestructable(x, y)
            PlayerSeeNoiseInRangeTimed(0.5, x, y)
        else
            RemoveDestructable(d)
            d = CreateDestructableZ(id, x, y, currentZ, 0, 2, 1)
        end
    end)
end

function RemoveTableDestructable(x, y)
    local range = 128
    SetRect(GlobalRect, x - range, y - range, x + range, y + range)
    EnumDestructablesInRect(GlobalRect, nil, function()
        local d = GetEnumDestructable()
        if GetDestructableTypeId(d) == FourCC("B00H") or GetDestructableTypeId(d) == FourCC("B005") then
            RemoveDestructable(d)
        end
    end)
end

function CreateSquareDestrutables(x, y)
    local id = FourCC("B005") -- B005 - невидимый,  B00H - видимый
    local t = {}
    local step = 64
    local nx, ny = x - step, y - step
    local d = CreateDestructableZ(id, nx, ny, GetTerrainZ(x, y), 0, 1, 1)
    table.insert(t, d)
    nx, ny = x + step, y + step
    d = CreateDestructableZ(id, nx, ny, GetTerrainZ(x, y), 0, 1, 1)
    table.insert(t, d)
    nx, ny = x - step, y + step
    d = CreateDestructableZ(id, nx, ny, GetTerrainZ(x, y), 0, 1, 1)
    table.insert(t, d)
    nx, ny = x + step, y - step
    d = CreateDestructableZ(id, nx, ny, GetTerrainZ(x, y), 0, 1, 1)
    table.insert(t, d)
    for i=1,#t do
        local dx,dy=GetDestructableX(t[i]),GetDestructableY(t[i])
        UnitDamageArea(udg_HERO,60,dx,dy,60,"All")
    end
end

function DownFloorInTimedXY(timed,nx,ny)
    local d = FindFloorInPoint(nx, ny)
    MoveDestructableDown(d, -500, 15)
    TimerStart(CreateTimer(), timed, false, function()
        d = FindFloorInPoint(nx, ny)
        MoveDestructableUp(d, 500, 5)
    end)
end