---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 28.11.2023 19:01
---
function CreateSplatXY(texture,x,y)
    --x,y=13043,2317
    --texture="imageR"
    local size=100
    local img = CreateImage(texture, size, size, size, 4000, 4000, 0, 0, 0, 1000, 3)
    --SetImageColor(img, 255, 255, 0, 128)
    SetImageRenderAlways(img, true)
    SetImagePosition(img,x-size/2,y-size/2,1000)
    ShowImage(img, true)

end
function InitRSFGHD()
    local t={
        "r",
        "s",
        "f",
        "g",
        "h",
        "d"
    }
    for i=1,#t do
        local texture="image"..t[i]
        local x,y=GetDestructableX(udg_Buttons[i]),GetDestructableY(udg_Buttons[i])
        CreateSplatXY(texture,x,y)
        --print(t[i])
    end
end