---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 16.04.2023 18:30
---
function ByItemByName(item)
    local data=HERO[0]
    if data.gold>=item.cost then
        --print("успешная покупка")
        data.gold=data.gold-item.cost
        item.cost=item.cost*2
        if not item.lvl then
            item.lvl=1
            --print("первая покупка")
        end
        item.lvl=item.lvl+1
        --print("lvl=",item.lvl)
        BlzFrameSetText(item.FHcost,item.cost)
        if not item.DS then
            item.isSold=true
            BlzFrameSetScale(item.FHcost,0.7)
            BlzFrameSetText(item.FHcost,"Продано")
        else
            if item.lvl>=#item.DS then
                item.isSold=true
                BlzFrameSetScale(item.FHcost,0.7)
                BlzFrameSetText(item.FHcost,"Продано")
            end
        end
    else
        print("недостаточно",item.cost-data.gold,"золота")
    end
end