---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 16.04.2023 14:49
---
function CreateShop()
    if SHOP then
        BlzFrameSetVisible(SHOP, true)
        return
    end
    SHOP = BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    InitItemBDForShop()
    --print(#SHOP_BD,SHOP_BD[1].descriptions)
    local rama = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SHOP, '', 0)
    local NextPoint = 0.039 + 0.011
    BlzFrameSetTexture(rama, "Textures\\Black32", 0, true) --HPElement
    BlzFrameSetSize(rama, 0.4, 0.3)
    BlzFrameSetAbsPoint(rama, FRAMEPOINT_CENTER, 0.4, 0.3)
    local x, y = 0.25, 0.4 - NextPoint
    local max = #SHOP_BD -- число предметов в БД магазина
    local k = 1
    for j = 1, 4 do
        for i = 1, 7 do
            if k <= max then
                CreateItemForShop(x + NextPoint * (i - 1), y - NextPoint * (j - 1), SHOP, SHOP_BD[k])
                k = k + 1
            end
        end
    end
    CreateCloseButton(SHOP, rama)
    CurrentGoldInShop(rama)
    CreateToolTipBox(rama)
end

function CreateItemForShop(posX, PosY, parent, item)
    local NextPoint = 0.039
    local cost = item.cost
    local name = item.name
    local descriptions = item.descriptions
    local texture = item.texture
    if not texture then
        texture = "ReplaceableTextures\\CommandButtons\\BTNSelectHeroOn"
    end
    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', parent, 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
    --BlzFrameSetVisible(SelfFrame, false)
    -- BlzFrameSetVisible(SelfFrame, GetLocalPlayer() == player)

    item.FHcost=ItemAddCostFromShop(buttonIconFrame, cost)
    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, texture, 0, true)
    BlzFrameSetSize(SelfFrame, NextPoint, NextPoint)
    BlzFrameSetAbsPoint(SelfFrame, FRAMEPOINT_CENTER, posX, PosY)

    local ClickTrig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(ClickTrig, SelfFrame, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(ClickTrig, function()
        --print("Нажата кнопка ")
        BlzFrameSetEnable(BlzGetTriggerFrame(), false)
        BlzFrameSetEnable(BlzGetTriggerFrame(), true)
        if not item.isSold then
            ByItemByName(item)
        end
    end)

    local TrigMOUSE_ENTER = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_ENTER, SelfFrame, FRAMEEVENT_MOUSE_ENTER)
    TriggerAddAction(TrigMOUSE_ENTER, function()
        --print("показать подсказку ",flag)
        BlzFrameSetText(SHOP_TOOLTIP, ColorText2(name) .. "\n" .. DSColorDescription(item))
    end)
    local TrigMOUSE_LEAVE = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_LEAVE, SelfFrame, FRAMEEVENT_MOUSE_LEAVE)
    TriggerAddAction(TrigMOUSE_LEAVE, function()
        --print("убрать подсказку")
        BlzFrameSetText(SHOP_TOOLTIP, "Если у вас достаточно золота, нажмите на иконку предмета левой кнопкой, чтобы купить его")
    end)
    return SelfFrame
end

function CreateToolTipBox(rama)
    local tooltip = BlzCreateFrameByType("FRAME", "TestDialog", rama, "StandardFrameTemplate", 0)
    local backdrop = BlzCreateFrame("QuestButtonDisabledBackdropTemplate", tooltip, 0, 0)
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", rama, "", 0)
    --BlzFrameSetAbsPoint(tooltip, FRAMEPOINT_CENTER, 0.04+0.04, 0.6-0.04-0.04)
    BlzFrameSetPoint(tooltip, FRAMEPOINT_TOP, rama, FRAMEPOINT_TOP, 0.00, 0.00)
    BlzFrameSetSize(tooltip, 0.18, 0.06)
    BlzFrameSetSize(backdrop, 0.2, 0.07)
    BlzFrameSetPoint(backdrop, FRAMEPOINT_CENTER, tooltip, FRAMEPOINT_CENTER, 0.0, 0.0)
    BlzFrameSetAlpha(backdrop, 100)

    BlzFrameSetSize(text, 0.18, 0.06)
    BlzFrameSetText(text, "Первичный текст")
    BlzFrameSetPoint(text, FRAMEPOINT_CENTER, backdrop, FRAMEPOINT_CENTER, 0.0, -0.005)
    --BlzFrameSetVisible(tooltip,false)
    SHOP_TOOLTIP = text
    --return tooltip,backdrop,text
end

function CurrentGoldInShop(parent)
    local goldIco = "Textures\\GOLDCoin.blp"
    local GoldFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', parent, '', 0)
    local data = HERO[0]
    BlzFrameSetParent(GoldFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(GoldFrame, goldIco, 0, true)
    BlzFrameSetSize(GoldFrame, NextPoint / 2, NextPoint / 2)
    BlzFrameSetPoint(GoldFrame, FRAMEPOINT_TOPLEFT, parent, FRAMEPOINT_TOPLEFT, 0.00, 0.00)

    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", GoldFrame, "", 0)
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, 9999)
    BlzFrameSetScale(text, 2)
    BlzFrameSetPoint(text, FRAMEPOINT_RIGHT, GoldFrame, FRAMEPOINT_RIGHT, 0.02, 0.0)
    TimerStart(CreateTimer(), 0.1, true, function()
        BlzFrameSetText(text, R2I(data.gold))
    end)
end

function ItemAddCostFromShop(FHItem, cost)
    local goldIco = "Textures\\GOLDCoin.blp"
    local GoldFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', FHItem, '', 0)
    BlzFrameSetParent(GoldFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(GoldFrame, goldIco, 0, true)
    BlzFrameSetSize(GoldFrame, NextPoint / 4, NextPoint / 4)
    BlzFrameSetPoint(GoldFrame, FRAMEPOINT_BOTTOMLEFT, FHItem, FRAMEPOINT_BOTTOMLEFT, 0.0005, -0.009)
    BlzFrameSetEnable(GoldFrame, false)
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", GoldFrame, "", 0)
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, cost)
    BlzFrameSetScale(text, 1)
    BlzFrameSetPoint(text, FRAMEPOINT_BOTTOMLEFT, GoldFrame, FRAMEPOINT_BOTTOMLEFT, 0.01, 0.0)
    BlzFrameSetEnable(text, false)
    return text
end

function CreateCloseButton(BoxBorder, rama)
    local NextPoint = 0.039
    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', BoxBorder, 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, "CloseCross", 0, true)
    BlzFrameSetSize(SelfFrame, NextPoint / 2, NextPoint / 2)
    BlzFrameSetPoint(SelfFrame, FRAMEPOINT_TOPRIGHT, rama, FRAMEPOINT_TOPRIGHT, 0.00, 0.00)
    local ClickTrig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(ClickTrig, SelfFrame, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(ClickTrig, function()
        --print("Закрыть")
        BlzFrameSetEnable(BlzGetTriggerFrame(), false)
        BlzFrameSetEnable(BlzGetTriggerFrame(), true)
        BlzFrameSetVisible(BoxBorder, false)
    end)
    local TrigMOUSE_ENTER = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_ENTER, SelfFrame, FRAMEEVENT_MOUSE_ENTER)
    TriggerAddAction(TrigMOUSE_ENTER, function()
        --print("показать подсказку ",flag)
        BlzFrameSetText(SHOP_TOOLTIP, "Нажмите чтобы закрыть магазин")
    end)
    local TrigMOUSE_LEAVE = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_LEAVE, SelfFrame, FRAMEEVENT_MOUSE_LEAVE)
    TriggerAddAction(TrigMOUSE_LEAVE, function()
        --print("убрать подсказку")
        BlzFrameSetText(SHOP_TOOLTIP, "Если у вас достаточно золота, нажмите на иконку предмета левой кнопкой, чтобы купить его")
    end)
end
NextPoint = 0.039
function CreateGoldInterFace(data)
    local goldIco = "Textures\\GOLDCoin.blp"
    local GoldFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetParent(GoldFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(GoldFrame, goldIco, 0, true)
    BlzFrameSetSize(GoldFrame, NextPoint / 2, NextPoint / 2)
    BlzFrameSetAbsPoint(GoldFrame, FRAMEPOINT_CENTER, 0.85, 0.02)
    BlzFrameSetVisible(GoldFrame, GetLocalPlayer() == Player(data.pid))

    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", GoldFrame, "", 0)
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, "0")
    BlzFrameSetScale(text, 2)
    BlzFrameSetPoint(text, FRAMEPOINT_RIGHT, GoldFrame, FRAMEPOINT_RIGHT, 0.02, 0.0)
    BlzFrameSetVisible(text, GetLocalPlayer() == Player(data.pid))
    BlzFrameSetText(text, data.gold)
    TimerStart(CreateTimer(), 0.1, true, function()
        BlzFrameSetText(text, R2I(data.gold))
    end)
end