---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 13.12.2021 0:39
---
function Blink2Point(unit, x, y)
    DestroyEffect(AddSpecialEffect("BlinkCasterNoOmni", GetUnitXY(unit)))
    SetUnitPositionSmooth(unit, x,y)
    DestroyEffect(AddSpecialEffect("BlinkCasterNoOmni", GetUnitXY(unit)))
end