---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 01.01.2023 17:35
---
function CastSnowBall(data, directionAngle)
    local effModel = "Firebrand Shot Silver"--snowball
    --effModel="PrismBeam_Initiate"

    local hero = data.UnitHero

    if data.AttackIsReady and not data.SpaceForce and UnitAlive(hero) and not FREE_CAMERA and not IsUnitStunned(hero) and not BlzFrameIsVisible(SHOP) then
        if GetUnitTypeId(hero) == HeroID then
            --WolfSlashAttack(hero) --для проверки вставлял
            BlzSetUnitFacingEx(hero, directionAngle)
            SetUnitAnimationByIndex(hero, 3)
            data.AttackIsReady = false
            data.UnitInAttack = true
            --CreateBeemLighting(hero)
            TimerStart(CreateTimer(), 0.15, false, function()
                -- задержка замаха
                CreateAndForceBullet(hero, directionAngle, 40, effModel,nil,nil,data.BaseDamage)
                if data.MorozkoCD then
                    if data.MorozkoCDCurrent<=0 then
                        local x,y=MoveXY(GetUnitX(hero),GetUnitY(hero),20,directionAngle-90)
                        CreateAndForceBullet(hero, directionAngle, 40, effModel,x,y,data.BaseDamage)
                        data.MorozkoCDCurrent=data.MorozkoCD
                        TimerStart(CreateTimer(), data.MorozkoCD, false, function()
                            data.MorozkoCDCurrent=0
                        end)
                    end
                end
                data.MHoldSec = data.MHoldSec + 1
                data.UnitInAttack = false
            end)
            TimerStart(CreateTimer(), data.AttackInterval, false, function() --0.35
                data.AttackIsReady = true
                if UnitAlive(hero) and not data.IsMoving and not LockAnimAnimation(data) then
                    ResetUnitAnimation(hero)
                end
                DestroyTimer(GetExpiredTimer())
            end)
        elseif GetUnitTypeId(hero) == FourCC("n002") then
            -- верхом на волке
           -- print("волк атакует рукой")
            WolfAttackPeon(hero, directionAngle)
        end
    end
end