---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 29.09.2023 15:11
---
function CHKBouncing(x, y, nx, ny, speed)
    local angle = AngleBetweenXY(x, y, nx, ny) / bj_DEGTORAD
    local has=false
    if not IsTerrainWalkable(nx, ny) then
        angle = 0 - (AngleBetweenXY(nx, ny, x, y) / bj_DEGTORAD)
        nx, ny = MoveXY(x, y, speed, angle)
        has=true
        if not IsTerrainWalkable(nx, ny) then
            angle = angle - 180
            has=true
        end
    end
    return angle,has
end

function CHKBouncingOLD(x, y, nx, ny)
    -- так и не заработало
    local A = {}
    A.x = x
    A.y = y

    A.v = Vector:new(nx - A.x, ny - A.y, 0.00)
    local x1 = 0
    local y1 = 0
    local b = {}
    local speed = 0.0000001
    print("avx", A.v.x)
    A.x = A.x + speed * A.v.x
    A.y = A.y + speed * A.v.y

    SetItemPosition(TempItem, A.x, A.y)
    SetItemVisible(TempItem, true)

    x = GetItemX(TempItem)
    y = GetItemY(TempItem)

    if (x - 1.00 > A.x or x + 1.00 < A.x) or (y - 1.00 > A.y or y + 1.00 < A.y) then
        print("первое условие")
        A.x = A.x - speed * A.v.x
        A.y = A.y - speed * A.v.y
        -- right
        x = A.x + 5.00
        y = A.y
        SetItemPosition(TempItem, x, y)
        SetItemVisible(TempItem, true)

        x1 = GetItemX(TempItem)
        y1 = GetItemY(TempItem)

        b[0] = (x1 - 1.00 > x or x1 + 1.00 < x) or (y1 - 1.00 > y or y1 + 1.00 < y)

        --left
        x = A.x - 5.00
        y = A.y
        SetItemPosition(TempItem, x, y)
        SetItemVisible(TempItem, true)

        x1 = GetItemX(TempItem)
        y1 = GetItemY(TempItem)
        b[1] = (x1 - 1.00 > x or x1 + 1.00 < x) or (y1 - 1.00 > y or y1 + 1.00 < y)

        -- up
        x = A.x
        y = A.y + 5.00
        SetItemPosition(TempItem, x, y)
        SetItemVisible(TempItem, true)

        x1 = GetItemX(TempItem)
        y1 = GetItemY(TempItem)
        b[2] = (x1 - 1.00 > x or x1 + 1.00 < x) or (y1 - 1.00 > y or y1 + 1.00 < y)

        -- down
        x = A.x
        y = A.y - 5.00
        SetItemPosition(TempItem, x, y)
        SetItemVisible(TempItem, true)

        x1 = GetItemX(TempItem)
        y1 = GetItemY(TempItem)
        b[3] = (x1 - 1.00 > x or x1 + 1.00 < x) or (y1 - 1.00 > y or y1 + 1.00 < y)

        if b[0] or b[1] or b[2] or b[3] then
            print("отражение")
            if b[0] or b[1] then
                A.v.x = -A.v.x
                print("b0b1")
            else
                A.v.y = -A.v.y
                print("b0b1 else")
            end
        else
            --print("b0b1b2b3 else")
            A.v.x = -A.v.x
            A.v.y = -A.v.y
        end
    end
    local angle = AngleBetweenXY(x1, y1, A.v.x, A.v.y) / bj_DEGTORAD
    print("угол отражения в итоге", angle)
    return angle
end