---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 08.03.2023 13:38
---
function CustomCinematicMode(state)
    --CinematicModeBJ(state, GetPlayersAll())
    if state then
        SetMusicVolumeBJ(20)
    else
        SetMusicVolumeBJ(100)
    end
    BlzHideOriginFrames(not state)
    local data=HERO[0]
    FREE_CAMERA=state
    data.ReleaseW=false
    data.ReleaseA=false
    data.ReleaseS=false
    data.ReleaseD=false
    data.IsMoving=false
    ResetUnitAnimation(data.UnitHero)
    BlzFrameSetVisible(BlzGetFrameByName("UpperButtonBarFrame", 0), not state)
    --BlzFrameSetVisible(BlzGetOriginFrame(ORIGIN_FRAME_PORTRAIT, 0), not state)
    BlzFrameSetVisible(BlzGetFrameByName("ResourceBarFrame", 0), not state)
    DrawSelectionPortrait(not state)
    if BugsFH[1] then
        for i=1,#BugsFH do
            BlzFrameSetVisible(BugsFH[i],false)
            --print("отображение старого босс бара?")
        end
    end
end