---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 15.11.2023 22:57
---
function InitDashVisualCharges(data)
    print(data.DashCharges, "максимум зарядов")
    data.TableDashEffect = {}
    for i = 1, data.DashCharges do
        local eff = AddSpecialEffect("1star", GetUnitXY(data.UnitHero))
        table.insert(data.TableDashEffect, eff)
    end
end
function RepositionCharges(data)
    for i = 1, #data.TableDashEffect do
        local z, x, y = GetUnitZ(data.UnitHero) + 110, GetUnitXY(data.UnitHero)
        if i == 1 then
            if data.DashCharges >= 1 then
                BlzSetSpecialEffectPosition(data.TableDashEffect[i], x - 20, y, z)
            else
                BlzSetSpecialEffectPosition(data.TableDashEffect[i], OutPoint, OutPoint, z)
            end
        elseif i == 2 then
            if data.DashCharges >= 2 then
                BlzSetSpecialEffectPosition(data.TableDashEffect[i], x, y, z)
            else
                BlzSetSpecialEffectPosition(data.TableDashEffect[i], OutPoint, OutPoint, z)
            end
        elseif i == 3 then
            if data.DashCharges >= 3 then
                BlzSetSpecialEffectPosition(data.TableDashEffect[i], x + 20, y, z)
            else
                BlzSetSpecialEffectPosition(data.TableDashEffect[i], OutPoint, OutPoint, z)
            end
        end
    end
end