---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 15.11.2023 22:57
---
function InitDashVisualCharges(data)
    --print(data.DashCharges, "максимум зарядов")
    data.TableDashEffect = {}
    for i = 1, data.DashCharges do
        local eff = AddSpecialEffectTarget("1starAttach"..i, data.UnitHero,"origin")
        table.insert(data.TableDashEffect, eff)
    end
end


function RepositionCharges(data)
    if data.DashCharges >= 3 then
        BlzPlaySpecialEffect(data.TableDashEffect[3],ANIM_TYPE_STAND)

    else
        BlzPlaySpecialEffect(data.TableDashEffect[3],ANIM_TYPE_DEATH)
    end
    if data.DashCharges >= 2 then
        BlzPlaySpecialEffect(data.TableDashEffect[2],ANIM_TYPE_STAND)

    else
        BlzPlaySpecialEffect(data.TableDashEffect[2],ANIM_TYPE_DEATH)
    end
    if data.DashCharges >= 1 then
        BlzPlaySpecialEffect(data.TableDashEffect[1],ANIM_TYPE_STAND)

    else
        BlzPlaySpecialEffect(data.TableDashEffect[1],ANIM_TYPE_DEATH)
    end
end
