---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 05.11.2023 15:53
---
function UnitStartFallAnim(hero, maxZ)
    StunUnit(hero, 5)
    SetUnitTimeScale(hero, 1)

    local z = GetUnitZ(hero) + maxZ
    local zNormal = GetUnitZ(hero)
    SetUnitZ(hero, z)
    local speed = 20
    TimerStart(CreateTimer(), 0.1, false, function()
        if GetUnitTypeId(hero) == FourCC("O000") then
            SetUnitAnimationByIndex(hero, 15)
        end
    end)
    local sb = false
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        z = z - speed
        SetUnitZ(hero, z)
        if z <= zNormal and not sb then
            sb = true
            local r = GetRandomInt(1, 3)
            local s = normal_sound("Sound\\Units\\Combat\\MetalHeavyBashFlesh" .. r, GetUnitXY(hero))
            local grow = GetRandomReal(0.5, 1)
            --print(grow)
            SetSoundPitch(s, grow)
            KillDestructableByTypeInPoint(ButtonsIDTable, 200, GetUnitXY(hero))
            if GetUnitTypeId(hero) == FourCC("O000") then
                r = GetRandomInt(1, 8)
                if r == 1 then
                    normal_sound("spine-bone-break-1", GetUnitXY(hero))
                    PlayMonoSpeech("Speech\\Peon\\Fall\\F" .. r, "Коленям после такого не жить")
                elseif r == 2 then
                    PlayMonoSpeech("Speech\\Peon\\Fall\\F" .. r, "Супер геройское приземление")
                elseif r == 3 then
                    PlayMonoSpeech("Speech\\Peon\\Fall\\F" .. r, "Опять приземлился на лицо")
                elseif r == 4 then
                    PlayMonoSpeech("Speech\\Peon\\Fall\\F" .. r, "Ещё пару таких падений я точно не переживу")
                elseif r == 5 then
                    normal_sound("spine-bone-break-1", GetUnitXY(hero))
                elseif r == 6 then
                    PlayMonoSpeech("Speech\\Peon\\Fall\\F" .. r, "На этот раз вроде ничего не сломал")
                elseif r == 7 then
                    PlayMonoSpeech("Speech\\Peon\\Fall\\F" .. r, "Тут высота не меньше 5 метров")
                elseif r == 8 then
                    PlayMonoSpeech("Speech\\Peon\\Fall\\F" .. r, "В лепёшку.... а нет, я в норме")
                end
            end
        end
        if z <= -200 then
            DestroyTimer(GetExpiredTimer())
            UnitRemoveStun(hero)
        end
    end)
end

function JumpToCenterRect(rect)
    --JumpToCenterRect(gg_rct_Exit00)
    --gg_rct_Region_038
    StunUnit(udg_HERO, 2)
    local x, y = GetRectCenterX(rect), GetRectCenterY(rect)
    local dist = DistanceBetweenXY(x, y, GetUnitXY(udg_HERO))
    local angle = -180 + AngleBetweenXY(x, y, GetUnitXY(udg_HERO)) / bj_DEGTORAD
    UnitAddJumpForce(udg_HERO, angle, 40, dist, 400)
    --ResetUnitCustomPause(boss)
end