---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 25.10.2023 20:17
---
function UnitCreateArtMissile(hero, angle, speed, distance, MaxHeight, HasMarker, effModel)
    local currentdistance = 0
    local i = 0
    local ZStart = GetUnitZ(hero)+40
    if not MaxHeight then
        MaxHeight = 0
    end
    local x, y = GetUnitXY(hero)
    local eff=AddSpecialEffect(effModel,x,y)
    local damage=50

    if IsUnitType(hero, UNIT_TYPE_HERO) then
        local data=GetUnitData(hero)
        damage=data.BaseDamage*2
    end

    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        currentdistance = currentdistance + speed
        local f = ParabolaZ(MaxHeight , distance, i * speed) + ZStart
        i = i + 1
        x,y=MoveXY(x,y,speed, angle)
        BlzSetSpecialEffectX(eff,x)
        BlzSetSpecialEffectY(eff,y)
        BlzSetSpecialEffectZ(eff,f)
        --BlzSetSpecialEffectScale(eff,5)
        if i > 3 and f <= GetTerrainZ(x, y) then
            DestroyTimer(GetExpiredTimer())
            UnitDamageArea(hero, damage, x, y, 200)
            if not effModel then
                --DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic", newX, newY))
            else
                DestroyEffect(eff)
                DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic", x, y))
            end
        end
    end)
end