---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 30.09.2023 16:57
---
--[[ -- закомменченно тут
RealGetUnitX = GetUnitX
RealGetUnitY = GetUnitY


function GetUnitRealX(unit)
    local collision = math.floor(BlzGetUnitCollisionSize(unit) + 0.5)

    if not IsUnitType(unit, UNIT_TYPE_STRUCTURE) then
        if (collision < 32 and collision > 15) or collision > 47 then return RealGetUnitX(unit) - 16. end
    end

    return RealGetUnitX(unit)
end

function GetUnitRealY(unit)
    local collision = math.floor(BlzGetUnitCollisionSize(unit) + 0.5)

    if not IsUnitType(unit, UNIT_TYPE_STRUCTURE) then
        if (collision < 32 and collision > 15) or collision > 47 then return RealGetUnitY(unit) - 16. end
    end

    return RealGetUnitY(unit)
end
--[[
local GetUnitRealX = GetUnitX
function GetUnitX(whichUnit)
    local collision = math.floor(BlzGetUnitCollisionSize(whichUnit) + 0.5)

    if not IsUnitType(whichUnit, UNIT_TYPE_STRUCTURE) then
        if (collision < 32 and collision > 15) or collision > 47 then
            return GetUnitRealX(whichUnit) - 16.
        end
    end
end


local GetUnitRealY = GetUnitY
function GetUnitY(whichUnit)
    local collision = math.floor(BlzGetUnitCollisionSize(whichUnit) + 0.5)

    if not IsUnitType(whichUnit, UNIT_TYPE_STRUCTURE) then
        if (collision < 32 and collision > 15) or collision > 47 then
            return GetUnitRealY(whichUnit) - 16.
        end
    end
    return GetUnitRealY(whichUnit)
end
]]

