---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 21.01.2023 11:44
---
function InitItems()
    local allUnitsItem = {}
    local idItems = {
        FourCC("h002"), -- леденец
    }
    for i = 1, #idItems do
        local unit = nil
        local e = nil
        local k = 0
        --print("ищем")

        GroupEnumUnitsInRect(perebor, bj_mapInitialPlayableArea, nil)
        while true do
            e = FirstOfGroup(perebor)

            if e == nil then
                break
            end
            if UnitAlive(e) and GetUnitTypeId(e) == idItems[i] then
                --print("найдено")
                table.insert(allUnitsItem, e)


            end
            GroupRemoveUnit(perebor, e)
        end
    end
    ------


    for i=1,#allUnitsItem do
        RegistryNewItem(allUnitsItem[i])
    end
end
function RegistryNewItem(unit)
    local enterTrig = CreateTrigger()
    TriggerRegisterUnitInRange(enterTrig, unit, 80, nil)
    TriggerAddAction(enterTrig, function()
        local entering = GetTriggerUnit()

        if GetUnitTypeId(entering)==HeroID and not IsUnitHidden(unit) then
            --print("вошел в зону предмета ",GetHandleId(unit))
            if GetUnitTypeId(unit)==FourCC("h002") then -- леденец
                --print("скушай леденец")
                HeroCandyHeal(GetUnitData(entering),1)
                local r=GetRandomInt(1,6)
                if r==1 then
                    PlayMonoSpeech("","Исцеление")
                elseif r==2 then
                    PlayMonoSpeech("","Вкусно!")
                elseif r==3 then
                    PlayMonoSpeech("","Конфетка!")
                elseif r==4 then
                    PlayMonoSpeech("","О, ещё конфетка!")
                elseif r==5 then
                    PlayMonoSpeech("","Это меня не много исцелит!")
                end
            end
            --KillUnit(unit)
            ShowUnit(unit,false)
            --print("убит ",GetHandleId(unit))
            local x,y=GetUnitXY(unit)
            TimerStart(CreateTimer(), 30, false, function()
                ShowUnit(unit,true)
                --CreateUnit(GetOwningPlayer(unit),GetUnitTypeId(unit),x,y,0)
            end)
        end
    end)
end