---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 30.11.2023 20:11
---

function InitEventUnitUnderPointer()
    local MouseMoveTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        local player = Player(i)
        TriggerRegisterPlayerEvent(MouseMoveTrigger, player, EVENT_PLAYER_MOUSE_MOVE)
    end

    local last=nil
    TriggerAddAction(MouseMoveTrigger, function()
        local FocusUnit=BlzGetMouseFocusUnit()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        if last~=FocusUnit and not data.CatchUnit  then
            if GetUnitTypeId(FocusUnit)==FourCC("h00C") then
               -- print(GetUnitName(FocusUnit))
                AddCircleAreaForUnit(FocusUnit, 525, 2)
            end
        end
        last=FocusUnit
    end)
end