---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 06.05.2023 22:21
---
function CHKVictory()
    TimerStart(CreateTimer(), 5, true, function()
        local victory = false
        if IsQuestCompleted(udg_QStarAnime) and IsQuestCompleted(udg_QYetty) and IsQuestCompleted(udg_QWine) and IsQuestCompleted(udg_QWolf) and IsQuestCompleted(udg_QDragon) then
            print("Все основные задания завершены, отправляйтесь к Траллу")
            victory = true
            DestroyTimer(GetExpiredTimer())
            UnitAddAbility(gg_unit_Oths_0011,FourCC("A604"))
        end
    end)
    --return victory
end