---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 03.03.2023 8:06
---
function CreateCustomPortrait()
    local parentBox = BlzCreateFrameByType('BACKDROP', "PORTRAIT", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetParent(parentBox, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetAbsPoint(parentBox, FRAMEPOINT_CENTER, 0.45, 0.3)
    BlzFrameSetSize(parentBox, 0.000001, 0.000001)

    CreateSprite("pico-boku-no-pico", parentBox, nil, 1,0,0.5)
    CreateSprite("68f000b0feac0213a64a5d1dc93b2365251874e5", parentBox, nil, 1,0.2,0.5)
    CreateSprite("6948ace06605aac9ab07548d22e72392aefc1278", parentBox, nil, 1,0.4,0.5)
    CreateSprite("cool", parentBox, nil, 1,0.6,0.5)
    CreateSprite("excalibur-soul-eater", parentBox, nil, 0.5,0,0.3)
    CreateSprite("jojos-noriaki-kakyoin", parentBox, nil, 0.3,0.2,0.3)
    CreateSprite("paimon", parentBox, nil, 1,0.4,0.3)
    CreateSprite("rock-one-eyebrow-raised-rock-staring", parentBox, nil, 1,0.6,0.2)
    CreateSprite("russia-ussr", parentBox, nil, 0.4,0,0.15)
    CreateSprite("stonks-up-stongs", parentBox, nil, 0.5,0.2,0.15)
    CreateSprite("sweaty-gamer-speedrun-whipping", parentBox, nil, 1,0.4,0.15)

end

function CreateSprite(path, parent, timed, scale, x, y)
    if not x then
        x = 0.4
    end
    if not y then
        y = 0.3
    end
    if not parent then
        parent=BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0)
    end
    local sprite = BlzCreateFrameByType("SPRITE", "justAName", parent, "WarCraftIIILogo", 0)
    BlzFrameClearAllPoints(sprite)
    BlzFrameSetAbsPoint(sprite, FRAMEPOINT_CENTER, x, y)
    BlzFrameSetSize(sprite, 0.00001, 0.00001)
    BlzFrameSetScale(sprite, scale)
    BlzFrameSetModel(sprite, path, 0)
    if timed then
        TimerStart(CreateTimer(), timed, false, function()
            BlzDestroyFrame(sprite)
        end)
    end
    return sprite
end