---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 23.01.2023 0:48
---
function CreateMiniCard()
    MiniCardBox = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0) -- глобалка всех карточек
    BlzFrameSetParent(MiniCardBox, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    MiniCARDFH={}
    for i = 1, 5 do
        local card = BlzCreateFrameByType("BACKDROP", "Face", MiniCardBox, "", 0)
        BlzFrameSetTexture(card, "CardEmpty", 0, true)
        BlzFrameSetSize(card, 0.05, 0.05)
        BlzFrameSetAbsPoint(card, FRAMEPOINT_CENTER, 0.79+(0.025*i), 0.02)
        table.insert(MiniCARDFH,card)
    end
end
function UnlockCard(texture,k)
    BlzFrameSetTexture(MiniCARDFH[k], texture, 0, true)
end