---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 05.03.2023 13:24
---
function CreateVictoryElderBorder()
    --GausBorder
    local alpha=255
    local BoxBorder = BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetParent(BoxBorder, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(BoxBorder, "GausBorder", 0, true)
    BlzFrameSetSize(BoxBorder, 1.6, 0.2)
    BlzFrameSetAbsPoint(BoxBorder, FRAMEPOINT_CENTER, 0.4, 0.3)

    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", BoxBorder, "", 0)
    BlzFrameSetPoint(text, FRAMEPOINT_CENTER, BoxBorder, FRAMEPOINT_CENTER, 0, 0)
    BlzFrameSetText(text, ColorText2("МОГУЧИЙ ВРАГ ПЕРЕИГРАН И УНИЧТОЖЕН"))
    BlzFrameSetScale(text, 4)

    local text2 = BlzCreateFrameByType("TEXT", "ButtonChargesText", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetPoint(text2, FRAMEPOINT_CENTER, BoxBorder, FRAMEPOINT_CENTER, 0, 0)
    BlzFrameSetText(text2, ColorText2("МОГУЧИЙ ВРАГ ПЕРЕИГРАН И УНИЧТОЖЕН"))
    BlzFrameSetScale(text2, 4.5)
    BlzFrameSetAlpha(text2, 20)
    local sec = 1
    local scale=4.5

    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        sec = sec - TIMER_PERIOD
        alpha=alpha-4
        --print(alpha)
        BlzFrameSetAlpha(BoxBorder,alpha)
        if alpha<=20 then
            BlzFrameSetAlpha(text2,alpha)
        end
        if sec<=0 then

        else
            scale=scale+0.02
            BlzFrameSetScale(text2, scale)
        end

        if alpha<10 then
            DestroyTimer(GetExpiredTimer())
            BlzDestroyFrame(BoxBorder)
            BlzDestroyFrame(text2)
        end
    end)
end