---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 14.01.2023 12:06
---
function CreateCardFrame()
    --print("создаём карточки")
    --BlzFrameSetAbsPoint(BlzGetFrameByName("ConsoleUIBackdrop", 0), FRAMEPOINT_TOPRIGHT, 0, 0) --на всякий
    CardBox = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0) -- глобалка всех карточек
    local cardNamesTable = {
        "CardGirland",
        "CardOlivie",
        "CardPresent",
        "CardStar",
        "CardVine",
    }
    local cardText = {
        "Гирлянда",
        "Салаты",
        "Подарки",
        "Звезда",
        "Вино",
    }
    --for i = 1, #cardNamesTable do
    local i=1
    TimerStart(CreateTimer(), 1, true, function()
        local card = BlzCreateFrameByType("BACKDROP", "Face", CardBox, "", 0)
        BlzFrameSetTexture(card, cardNamesTable[i], 0, true)
        BlzFrameSetSize(card, 0.26, 0.26)
        BlzFrameSetAbsPoint(card, FRAMEPOINT_CENTER, 0.13 + ((i - 1) * 0.12), 0.4)

        local textName = BlzCreateFrameByType("TEXT", "ButtonChargesText", card, "", 0)
        BlzFrameSetText(textName, cardText[i])
        BlzFrameSetPoint(textName, FRAMEPOINT_BOTTOM, card, FRAMEPOINT_BOTTOM, 0., 0.025)
        if true then
            local alpha = 0
            BlzFrameSetAlpha(card, alpha)
           -- print(alpha)
            TimerStart(CreateTimer(), 0.01, true, function()
                alpha = alpha + 1
                BlzFrameSetAlpha(card, alpha)
                if alpha >= 255 then
                    if i>=5 then
                        --print("создание карточек завершено")
                    end
                    DestroyTimer(GetExpiredTimer())
                end
            end)
        end

        --BlzFrameSetParent(card, BlzGetFrameByName("ConsoleUIBackdrop", 0))
        i=i+1
        if i==6 then
            DestroyTimer(GetExpiredTimer())
        end
    end)

end

