---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 04.02.2023 20:12
---
peonRescue = 0
peonRescueMax = 50
function CreatePeonCounter()
    --print("111111111111111111111")
    local box = BlzCreateFrameByType('BACKDROP', 'Face', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetParent(box, BlzGetFrameByName("ConsoleUIBackdrop", 0))

    local peon = BlzCreateFrameByType("BACKDROP", "Face", box, "", 0)

    BlzFrameSetTexture(peon, "ReplaceableTextures\\CommandButtons\\BTNPeon.blp", 0, true)
    BlzFrameSetSize(peon, 0.05, 0.05)
    BlzFrameSetAbsPoint(peon, FRAMEPOINT_CENTER, -0.11, 0.025) ---0.11, 0.025

    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", peon, "", 0)

    BlzFrameSetPoint(text, FRAMEPOINT_RIGHT, peon, FRAMEPOINT_RIGHT, 0.025, 0.)
    -- BlzFrameSetSize(text, 0.05, 0.05)
    local change=peonRescue
    TimerStart(CreateTimer(), 1, true, function()
        BlzFrameSetText(text, peonRescue .. "/" .. peonRescueMax)
        if change<peonRescue then
            change=peonRescue
            --print("значение изменилось")
            ShowFrameTimed(box)
        end
    end)
    BlzFrameSetScale(text, 2)
    BlzFrameSetVisible(box,false)
end

function ShowFrameTimed(fh)
    if not BlzFrameIsVisible(fh) then
        BlzFrameSetVisible(fh,true)
        TimerStart(CreateTimer(), 1, false, function()
            BlzFrameSetVisible(fh,false)
        end)
    end
end
