---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 12.03.2023 13:39
---
function CreateQTEFrame()
    local QTE = BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetParent(QTE, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(QTE, "HadesE", 0, true)
    BlzFrameSetSize(QTE, 0.05, 0.05)
    BlzFrameSetAbsPoint(QTE, FRAMEPOINT_CENTER, 0.44, 0.3)

    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", QTE, "", 0)
    BlzFrameSetPoint(text, FRAMEPOINT_LEFT, QTE, FRAMEPOINT_LEFT, 0.02, 0)
    BlzFrameSetText(text, ColorText2("чтобы освободиться"))
    BlzFrameSetScale(text, 2)
    CreateJumpArrow(QTE)
    return QTE
end

function CreateJumpArrow(parent)
    local x=0.02
    local speed=0.1
    local arrow = BlzCreateFrameByType("BACKDROP", "Face", parent, "", 0)
    BlzFrameSetParent(arrow, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(arrow, "ArrowDown", 0, true)
    BlzFrameSetSize(arrow, 0.05, 0.05)
    local i=0
    local duration=5
    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        local y=math.sin(i)*x
        duration=duration-TIMER_PERIOD
       -- print(y)
        i=i+speed
        BlzFrameSetPoint(arrow,FRAMEPOINT_TOP,parent,FRAMEPOINT_TOP,0,y+0.04)
        if duration<=0 then
            DestroyTimer(GetExpiredTimer())
        end
    end)
end

function CreateEActions()
    -----------------------------------------------------------------OSKEY_E
    local gg_trg_EventUpE = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpE, Player(i), OSKEY_E, 0, true)
    end
    TriggerAddAction(gg_trg_EventUpE, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        if not data.ReleaseE and UnitAlive(data.UnitHero) then
            data.ReleaseE = true
            --StartEatingApple(data.UnitHero) -- УДАЛИТЬ!!
            --print("нажал Е")
            if QTEReadyToPress then
                QTEReadyToPress=false
                --print("нажал Е во время QTE")
            end
        end
    end)

    local TrigDepressE = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(TrigDepressE, Player(i), OSKEY_E, 0, false)
    end
    TriggerAddAction(TrigDepressE, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        data.ReleaseE = false
    end)
end