---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 12.03.2023 16:11
---
function CreateMouseHelper()
    local wood=BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetTexture(wood, "RMB", 0, true)
    BlzFrameSetSize(wood, 0.15, 0.15)
    BlzFrameSetAbsPoint(wood, FRAMEPOINT_CENTER,0.1 , 0.4)

    local new_FrameChargesText = BlzCreateFrameByType("TEXT", "ButtonChargesText", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetAbsPoint(new_FrameChargesText, FRAMEPOINT_CENTER, 0.1, 0.31)
    BlzFrameSetText(new_FrameChargesText, "Удерживайте LMB, чтобы стрелять")

    local new_FrameChargesText2 = BlzCreateFrameByType("TEXT", "ButtonChargesText", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetAbsPoint(new_FrameChargesText2, FRAMEPOINT_CENTER, 0.1, 0.17)
    BlzFrameSetText(new_FrameChargesText2, "Нажимайте WASD, чтобы двигаться \nНажимайте RMB, чтобы стрелять по области \nУдерживайте R для перезапуска уровня ")

    local new_FrameChargesText3 = BlzCreateFrameByType("TEXT", "ButtonChargesText", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetAbsPoint(new_FrameChargesText3, FRAMEPOINT_CENTER, 0.1, 0.29)
    BlzFrameSetText(new_FrameChargesText3, "Space - рывок в направлении движения")

    local wasd = BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetTexture(wasd, "WASD", 0, true)
    BlzFrameSetSize(wasd, 0.10, 0.10)
    BlzFrameSetAbsPoint(wasd, FRAMEPOINT_CENTER, 0.1, 0.25)

    TimerStart(CreateTimer(), 1, true, function()
        local data = HERO[0]

        if data.MHoldSec >= 6 then
            BlzFrameSetVisible(new_FrameChargesText, false)
            BlzFrameSetVisible(wood, false)
            BlzFrameSetVisible(wasd, false)
            BlzFrameSetVisible(new_FrameChargesText2, false)
            BlzFrameSetVisible(new_FrameChargesText3, false)
        end
    end)
end

function CreateGirlandUI()
    local g1 = BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetParent(g1, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(g1, "UIGirland", 0, true)
    BlzFrameSetSize(g1, 0.10, 0.4)
    BlzFrameSetAbsPoint(g1, FRAMEPOINT_CENTER, -0.12, 0.4)

    local g2 = BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetParent(g2, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(g2, "UIGirland", 0, true)
    BlzFrameSetSize(g2, 0.10, 0.4)
    BlzFrameSetAbsPoint(g2, FRAMEPOINT_CENTER, 0.93, 0.4)

end